### ISSUE TITLE
Feedback on apitte@0.9

### ISSUE THREAD

**Issue by f3l1x** [contributte/apitte#174]
Apitte has been melted to single one package. 

See more on https://github.com/contributte/contributte/issues/50. 

----

How to test it?

```json
{
  "require": {
    "contributte/apitte": "^0.9.0"
  },
  "prefer-stable": true,
  "minimum-stability": "dev"
}
```

**Comment by northys** [comment]
upgraded and it works

**Comment by Roman3349** [comment]
Some commits (e.g. https://github.com/contributte/apitte-core/commit/8cdf154b05d355598e5deca25ad07aeb587e7f64 and https://github.com/contributte/apitte-core/commit/e114cfa747977972ceb77e059d474eb00b1edf76) are missing.

**Comment by khorsky** [comment]
When using middlewares, man must manually register middleware extension.

That information is missing in [doc page](https://github.com/contributte/apitte/blob/master/.docs/middlewares.md) of this package, one has to dig through apitte/middleware documentation, which I find a bit strange...

**Comment by f3l1x** [comment]
Thank you @khorsky.

**Comment by f3l1x** [comment]
@khorsky added, https://github.com/contributte/apitte/commit/0281c99b1e18890a1e5df6ad9dd47cab8a72aa12

**Comment by f3l1x** [comment]
Thank you for your feedback @darkWolf-PR. I will try to update docs.

**Comment by f3l1x** [comment]
Closing here
