### ISSUE TITLE
Fatal Error: During inheritance of IteratorAggregate

### ISSUE THREAD

**Issue by xpackal5** [contributte/apitte#192]
If you are using PHP8.1 RequestEntity throws

`Fatal Error: During inheritance of IteratorAggregate: Uncaught  in /var/www/html/vendor/apitte/core/src/Mapping/Request/AbstractEntity.php:9`

**Comment by Roman3349** [comment]
@xpackal5 It was fixed in https://github.com/contributte/apitte/commit/575669781dc905405a7bd8179dd546b21d4ee953. Please upgrade apitte to at least version [0.9.1](https://github.com/contributte/apitte/releases/tag/v0.9.1).

**Comment by xpackal5** [comment]
OK it helps. I was using apitte/fullstack whitch was abandoned
