### ISSUE TITLE
No matched route by given URL

### ISSUE THREAD

**Issue by radekdostal** [contributte/apitte#202]
Since version 0.10.0 without changing the code an error is always thrown "Apitte\Core\Exception\Api\ClientErrorException #404 No matched route by given URL".

After downgrading to 0.9.1, everything works better.

PHP 8.2

**Comment by radekdostal** [comment]
The absolute simplest example, I have one controller and one method.

```php
// BaseV1Controller.php
/**
 * @Path("/v1")
 */
abstract class BaseV1Controller implements IController {}

// UserController.php
/**
 * @Path("/users")
 */
final class UserController extends BaseV1Controller
{
  /**
   * @Path("/")
   * @Method("GET")
   */
  public function getAll(ApiRequest $request, ApiResponse $response): ApiResponse
  {
    ...
  }
}

// config.neon
extensions:
  api: Apitte\Core\DI\ApiExtension

api:
  catchException: TRUE
  debug: %debugMode%
  plugins:
    Apitte\Core\DI\Plugin\CoreDecoratorPlugin:
    Apitte\Debug\DI\DebugPlugin:
      debug:
        panel: %debugMode%
        negotiation: %debugMode%

services:
  - App\Controllers\UserController()

// index.php
// ...
App\Bootstrap::boot()
  ->createContainer()
  ->getByType(Apitte\Core\Application\IApplication::class)
  ->run();

GET https://web.localhost/<project-url>/v1/users
```

**Comment by f3l1x** [comment]
Hmm, I see some troubles at `<project-url>`, can you give a try https://github.com/contributte/middlewares/blob/master/.docs/README.md#autobasepathmiddleware?

**Comment by f3l1x** [comment]
Hmm, I am lost. I don't use setup `https://web.localhost/<project-url>/v1/users` thus I don't know where is the catch. 

Can you please setup https://github.com/contributte/apitte-skeleton/ as you have a and write a little manual for me how to setup webserver routing as you have?

**Comment by radekdostal** [comment]
I ran apitte-skeleton on Apache (without Docker) and it's still the same. The base URL of the app is https://web.localhost/aplikace/www/apitte-skeleton-master/www. Then I try https://web.localhost/aplikace/www/apitte-skeleton-master/www/api/v1/users and it always ends with "No matched route by given URL".

**Comment by f3l1x** [comment]
I run apitte-skeleton on webhosting, https://examples.contributte.org/apitte-skeleton/api/v1/users and routing works.

`local.neon` file:

```neon
services:
        middleware.basepath:
                factory: Contributte\Middlewares\AutoBasePathMiddleware
                tags:
                        middleware:
                                priority: 10
```

**Comment by radekdostal** [comment]
Yes, I get the 401 error as well, but if I remove middleware.authenticator, it ends up with the same error again "No matched route by given URL", even though I set middleware.basepath.

**Comment by radekdostal** [comment]
Yes, it works! But I had to use the middleware autobasepath in my application.
